CREATE TRIGGER INTERNAMENTO_INSERT
AFTER INSERT ON INTERNAMENTO
FOR EACH ROW
WHEN NEW.dataDeEntrada < (SELECT data FROM CONSULTA WHERE id = NEW.consulta)
BEGIN
    UPDATE INTERNAMENTO
    SET dataDeEntrada = (SELECT data FROM CONSULTA WHERE id = NEW.consulta)
    WHERE id = NEW.id;
END;
