PRAGMA foreign_keys = ON;

DELETE FROM R_ENFERMEIRO_INTERNAMENTO;
DELETE FROM R_MANUTENCAO;
DELETE FROM R_EQUIPAMENTO_SALA_DE_EXAME;
DELETE FROM R_ESPECIALIDADE_EQUIPAMENTO;
DELETE FROM R_MEDICO_ESPECIALIDADE;
DELETE FROM INTERNAMENTO;
DELETE FROM EQUIPAMENTO;
DELETE FROM CONSULTA;
DELETE FROM SALA_DE_EXAME;
DELETE FROM UTENTE;
DELETE FROM ESPECIALIDADE;
DELETE FROM TECNICO;
DELETE FROM ENFERMEIRO;
DELETE FROM MEDICO;
DELETE FROM FUNCIONARIO;

--Staff do hospital
INSERT INTO "FUNCIONARIO" VALUES (1, 'Mario', '2001-05-01', '2015-02-03');
INSERT INTO "TECNICO" VALUES (1);
INSERT INTO "FUNCIONARIO" VALUES (2, 'Maria', '2001-04-01', '2016-02-03');
INSERT INTO "MEDICO" VALUES (2);
INSERT INTO "FUNCIONARIO" VALUES (3, 'Joao', '1999-01-01', '2020-03-03');
INSERT INTO "ENFERMEIRO" VALUES (3);
INSERT INTO "FUNCIONARIO" VALUES (4, 'Andre', '1996-01-26', '2015-02-03');
INSERT INTO "TECNICO" VALUES (4);
INSERT INTO "FUNCIONARIO" VALUES (5, 'Joana', '2000-10-20', '2016-02-03');
INSERT INTO "MEDICO" VALUES (5);
INSERT INTO "FUNCIONARIO" VALUES (6, 'Andreia', '1998-03-14', '2019-04-21');
INSERT INTO "ENFERMEIRO" VALUES (6);
INSERT INTO "FUNCIONARIO" VALUES (7, 'Cesar', '1990-12-12', '2015-10-09');
INSERT INTO "MEDICO" VALUES (7);
INSERT INTO "FUNCIONARIO" VALUES (8, 'Antónia', '1999-08-22', '2021-01-19');
INSERT INTO "MEDICO" VALUES (8);

--Especialidades
INSERT INTO "ESPECIALIDADE" VALUES (1, 1,'Esquerda', 10, 2);
INSERT INTO "ESPECIALIDADE" VALUES (2, 2,'Esquerda', 12, 5);
INSERT INTO "ESPECIALIDADE" VALUES (3, 1,'Direita', 8, 7);

--Utentes
INSERT INTO "UTENTE" VALUES (1, 'Zeca', '2018-02-02');
INSERT INTO "UTENTE" VALUES (2, 'Matilde', '1980-09-04');
INSERT INTO "UTENTE" VALUES (3, 'Ricardo', '2000-12-16');
INSERT INTO "UTENTE" VALUES (4, 'Ana', '1960-07-30');
INSERT INTO "UTENTE" VALUES (5, 'Mariana', '2005-08-05');

--Salas de exame
INSERT INTO "SALA_DE_EXAME" VALUES (1, 10, 1);
INSERT INTO "SALA_DE_EXAME" VALUES (2, 12, 2);
INSERT INTO "SALA_DE_EXAME" VALUES (3, 12, 3);

--Consultas
INSERT INTO "CONSULTA" VALUES (1, '2021-03-28', 'Queda das escadas.', 'normal', 2, 1, 1, 1);
INSERT INTO "CONSULTA" VALUES (2, '2021-03-29', 'Dores no peito.', 'grave', 7, 3, 2, 3);
INSERT INTO "CONSULTA" VALUES (3, '2021-03-30', 'Febre moderada.', 'normal', 8, 3, 5, 3);
INSERT INTO "CONSULTA" VALUES (4, '2021-03-31', 'Atropelamento.', 'muito grave', 2, 1, 3, 1);

--Equipamento
INSERT INTO "EQUIPAMENTO" VALUES (1,'Vacina do covid', '222222', '2021-06-01');

--Internamento
INSERT INTO "INTERNAMENTO" VALUES (1, '2021-03-29', '2021-04-06', 'Descanso.', 1, 2);
INSERT INTO "INTERNAMENTO" VALUES (2, '2021-03-31', '2021-04-10', 'Operação de reconstrução.', 2, 4);

--Relação entre médico e especialidade
INSERT INTO "R_MEDICO_ESPECIALIDADE" VALUES (2, 1);
INSERT INTO "R_MEDICO_ESPECIALIDADE" VALUES (5, 2);
INSERT INTO "R_MEDICO_ESPECIALIDADE" VALUES (7, 3);
INSERT INTO "R_MEDICO_ESPECIALIDADE" VALUES (8, 3);

--Relação entre especialidade e equipamento
INSERT INTO "R_ESPECIALIDADE_EQUIPAMENTO" VALUES (3, 1, 50);

--Relação entre equipamento e sala de exame
INSERT INTO "R_EQUIPAMENTO_SALA_DE_EXAME" VALUES (1, 2, 25);

--Relação entre técnicos e as salas pelas quais são reponsáveis
INSERT INTO "R_MANUTENCAO" VALUES (1, 1);
INSERT INTO "R_MANUTENCAO" VALUES (1, 2);
INSERT INTO "R_MANUTENCAO" VALUES (4, 3);

--Relação entre enfermeiros e os internamentos pelos quais são reponsáveis
INSERT INTO "R_ENFERMEIRO_INTERNAMENTO" VALUES (3,1);
INSERT INTO "R_ENFERMEIRO_INTERNAMENTO" VALUES (6,2);
