PRAGMA foreign_keys = ON;

DELETE FROM R_ENFERMEIRO_INTERNAMENTO;
DELETE FROM R_MANUTENCAO;
DELETE FROM R_EQUIPAMENTO_SALA_DE_EXAME;
DELETE FROM R_ESPECIALIDADE_EQUIPAMENTO;
DELETE FROM R_MEDICO_ESPECIALIDADE;
DELETE FROM INTERNAMENTO;
DELETE FROM EQUIPAMENTO;
DELETE FROM CONSULTA;
DELETE FROM SALA_DE_EXAME;
DELETE FROM UTENTE;
DELETE FROM ESPECIALIDADE;
DELETE FROM TECNICO;
DELETE FROM ENFERMEIRO;
DELETE FROM MEDICO;
DELETE FROM FUNCIONARIO;

--Staff do hospital
INSERT INTO "FUNCIONARIO" VALUES (1, 'Mario', '20010501', '20150203');
INSERT INTO "TECNICO" VALUES (1);
INSERT INTO "FUNCIONARIO" VALUES (2, 'Maria', '20010401', '20160203');
INSERT INTO "MEDICO" VALUES (2);
INSERT INTO "FUNCIONARIO" VALUES (3, 'Joao', '19990101', '20200303');
INSERT INTO "ENFERMEIRO" VALUES (3);
INSERT INTO "FUNCIONARIO" VALUES (4, 'Andre', '19960126', '20150203');
INSERT INTO "TECNICO" VALUES (4);
INSERT INTO "FUNCIONARIO" VALUES (5, 'Joana', '20001020', '20160203');
INSERT INTO "MEDICO" VALUES (5);
INSERT INTO "FUNCIONARIO" VALUES (6, 'Andreia', '19980314', '20190421');
INSERT INTO "ENFERMEIRO" VALUES (6);
INSERT INTO "FUNCIONARIO" VALUES (7, 'Cesar', '19901212', '20151009');
INSERT INTO "MEDICO" VALUES (7);
INSERT INTO "FUNCIONARIO" VALUES (8, 'Antónia', '19990822', '20210119');
INSERT INTO "MEDICO" VALUES (8);

--Especialidades
INSERT INTO "ESPECIALIDADE" VALUES (1,'Esquerda', 10, 2);
INSERT INTO "ESPECIALIDADE" VALUES (2,'Esquerda', 12, 5);
INSERT INTO "ESPECIALIDADE" VALUES (1,'Direita', 8, 7);

--Utentes
INSERT INTO "UTENTE" VALUES (1, 'Zeca', '20180202');
INSERT INTO "UTENTE" VALUES (2, 'Matilde', '19800904');
INSERT INTO "UTENTE" VALUES (3, 'Ricardo', '20001216');
INSERT INTO "UTENTE" VALUES (4, 'Ana', '19600730');
INSERT INTO "UTENTE" VALUES (5, 'Mariana', '20050805');

--Salas de exame
INSERT INTO "SALA_DE_EXAME" VALUES (1, 10, 1, 'Esquerda');
INSERT INTO "SALA_DE_EXAME" VALUES (2, 12, 2, 'Esquerda');
INSERT INTO "SALA_DE_EXAME" VALUES (3, 12, 1, 'Direita');

--Consultas
INSERT INTO "CONSULTA" VALUES (1, '20210328', 'Queda das escadas.', 'normal', 2, 1, 'Esquerda', 1, 1);
INSERT INTO "CONSULTA" VALUES (2, '20210329', 'Dores no peito.', 'grave', 7, 1, 'Direita', 2, 3);
INSERT INTO "CONSULTA" VALUES (3, '20210330', 'Febre moderada.', 'normal', 8, 1, 'Direita', 5, 3);
INSERT INTO "CONSULTA" VALUES (4, '20210331', 'Atropelamento.', 'muito grave', 2, 1, 'Esquerda', 3, 1);

--Equipamento
INSERT INTO "EQUIPAMENTO" VALUES (1,'Vacina do covid', '222222', '20210601');

--Internamento
INSERT INTO "INTERNAMENTO" VALUES (1, '20210329', '20210406', 'Descanso.', 1, 2);
INSERT INTO "INTERNAMENTO" VALUES (2, '20210331', '20210410', 'Operação de reconstrução.', 2, 4);

--Relação entre médico e especialidade
INSERT INTO "R_MEDICO_ESPECIALIDADE" VALUES (2, 1, 'Esquerda');
INSERT INTO "R_MEDICO_ESPECIALIDADE" VALUES (5, 2, 'Esquerda');
INSERT INTO "R_MEDICO_ESPECIALIDADE" VALUES (7, 1, 'Direita');
INSERT INTO "R_MEDICO_ESPECIALIDADE" VALUES (8, 1, 'Direita');

--Relação entre especialidade e equipamento
INSERT INTO "R_ESPECIALIDADE_EQUIPAMENTO" VALUES (1, 'Direita', 1, 50);

--Relação entre equipamento e sala de exame
INSERT INTO "R_EQUIPAMENTO_SALA_DE_EXAME" VALUES (1, 2, 25);

--Relação entre técnicos e as salas pelas quais são reponsáveis
INSERT INTO "R_MANUTENCAO" VALUES (1, 1);
INSERT INTO "R_MANUTENCAO" VALUES (1, 2);
INSERT INTO "R_MANUTENCAO" VALUES (4, 3);

--Relação entre enfermeiros e os internamentos pelos quais são reponsáveis
INSERT INTO "R_ENFERMEIRO_INTERNAMENTO" VALUES (3,1);
INSERT INTO "R_ENFERMEIRO_INTERNAMENTO" VALUES (6,2);
